platform :ios, :deployment_target => '5.0'
pod 'Nimbus/Core', '0.9.3'
pod 'Nimbus/Models', '0.9.3'
pod 'Nimbus/NetworkControllers', '0.9.3'
pod 'Nimbus/PagingScrollView', '0.9.3'
pod 'Nimbus/Photos', '0.9.3'
pod 'Nimbus/Overview', '0.9.3'
pod 'Nimbus/WebController', '0.9.3'
pod 'AFNetworking', '=1.0RC1'
pod 'A2DynamicDelegate'
pod 'BlocksKit'
pod 'SDURLCache'
pod 'SVProgressHUD', '=0.7'
pod 'MJPopupViewController'
pod 'DDProgressView'
pod 'FPPopover'
pod 'iCarousel'
pod 'AFIncrementalStore'
